version: '3'
services:
  hyperliquid-stats-web:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    environment:
      NEXT_PUBLIC_API_URL: /api
      PORT: 80

  web:
    image: nginx:alpine
    ports:
      - "3002:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
